# This is the development workflow. It will do a clean install of node dependencies, cache/restore them, build the source code and run tests 

name: Development CI

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm packages
      run: npm i

    - name: Run app in production mode
      run: npm run start

    - name: run tests
      run: npm run ciTest
